services:
  postgres:
    container_name: postgresdb
    image: postgres:latest
    environment:
      POSTGRES_DB: favstocksdb
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /data/postgres
    ports:
      - 5433:5432
    networks:
      - stockServiceNetwork
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U me"]
      interval: 5s
      retries: 5
      start_period: 5s

  back_end_service:
    build: ./BackEnd/StockApp
    container_name: backEndService
    environment:
      POSTGRES_DB: favstocksdb
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - 8081:8080
    depends_on: 
      postgres:
       condition: service_healthy
    networks:
      - stockServiceNetwork

  front_end_service:
    build: ./FrontEnd/StockAppUI
    container_name: frontEndService
    ports:
      - 4201:80
    networks:
      - stockServiceNetwork

networks:
  stockServiceNetwork:
    name: stockServiceNetwork
    driver: bridge

volumes:
  postgres: